### ISSUE TITLE
Helm parses commit hash when using --set-string

### ISSUE THREAD

**Issue by lojzatran** [commercetools/k8s-charts#33]
We had a problem before that was explained in this PR: https://github.com/commercetools/k8s-charts/pull/32

The PR above should have fixed the problem, but it did not. The problem is still here and it failed us on commit with hash `574985703c044b969a5e8bd3231351a5d8e59e6c`. It produces a image tag `5.749857e+07`, which is not valid.

**Comment by LEQADA** [comment]
Thank you for the issue @lojzatran. Could you share which version of k8s-charts and helm are you using?

**Comment by lojzatran** [comment]
```
HELM_VERSION="v2.14.3"
HELM_CHARTS_VERSION="1.7.4"
```

**Comment by lojzatran** [comment]
After consultation with @LEQADA we discovered there is no bug and this issue can be closed.
